-- AlterTable
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "showInSidebar" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "sidebarName" TEXT;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "sidebarPosition" INTEGER;
